// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A flow that sends appointment reminders to patients as their turn approaches.
 *
 * - sendAppointmentReminders - A function that sends appointment reminders to patients.
 * - SendAppointmentRemindersInput - The input type for the sendAppointmentReminders function.
 * - SendAppointmentRemindersOutput - The return type for the sendAppointmentReminders function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SendAppointmentRemindersInputSchema = z.object({
  patientName: z.string().describe('The name of the patient.'),
  phoneNumber: z.string().describe('The phone number of the patient.'),
  appointmentTime: z.string().describe('The scheduled appointment time.'),
  estimatedWaitTime: z.string().describe('The estimated wait time for the patient.'),
  clinicName: z.string().describe('The name of the clinic.'),
});
export type SendAppointmentRemindersInput = z.infer<typeof SendAppointmentRemindersInputSchema>;

const SendAppointmentRemindersOutputSchema = z.object({
  messageSent: z.boolean().describe('Whether the appointment reminder message was successfully sent.'),
  messageContent: z.string().describe('The content of the appointment reminder message.'),
});
export type SendAppointmentRemindersOutput = z.infer<typeof SendAppointmentRemindersOutputSchema>;

export async function sendAppointmentReminders(input: SendAppointmentRemindersInput): Promise<SendAppointmentRemindersOutput> {
  return sendAppointmentRemindersFlow(input);
}

const sendAppointmentRemindersPrompt = ai.definePrompt({
  name: 'sendAppointmentRemindersPrompt',
  input: {schema: SendAppointmentRemindersInputSchema},
  output: {schema: SendAppointmentRemindersOutputSchema},
  prompt: `You are an AI assistant that sends appointment reminders to patients.

  Compose a personalized appointment reminder message to the patient, informing them of their upcoming appointment.
  Include the clinic name, appointment time, and estimated wait time.
  Ensure the message is concise and friendly.

  Patient Name: {{{patientName}}}
  Phone Number: {{{phoneNumber}}}
  Appointment Time: {{{appointmentTime}}}
  Estimated Wait Time: {{{estimatedWaitTime}}}
  Clinic Name: {{{clinicName}}}

  Compose the message and indicate whether it was successfully sent.
  `,
});

const sendAppointmentRemindersFlow = ai.defineFlow(
  {
    name: 'sendAppointmentRemindersFlow',
    inputSchema: SendAppointmentRemindersInputSchema,
    outputSchema: SendAppointmentRemindersOutputSchema,
  },
  async input => {
    const {output} = await sendAppointmentRemindersPrompt(input);
    // Here, ideally, you would integrate with a messaging service like Twilio
    // to actually send the SMS. For this example, we'll just simulate it.
    console.log("Simulating sending SMS to", input.phoneNumber, "with message:", output?.messageContent);
    return {
      messageSent: true, // Assume message was sent successfully
      messageContent: output?.messageContent || 'Appointment reminder', // Provide a default value if messageContent is undefined
    };
  }
);
