// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  "projectId": "queuewise-6l2c7",
  "appId": "1:624917397957:web:53c1a9f4b1189a04c94bac",
  "apiKey": "AIzaSyCkWWkGzTmQadQZD5PYf0J73xMmivwfXJI",
  "authDomain": "queuewise-6l2c7.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "624917397957"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);

export { app, db };
